-- GameConfig
-- Constantes globales del juego
-- Ubicación: ReplicatedStorage > Modules > GameConfig (ModuleScript)

local GameConfig = {
	STARTING_CELLS = 500,

	BARRIER_MAX_HP = 1000,
	BARRIER_REPAIR_COST = 80,
	BARRIER_REPAIR_AMOUNT = 100,
	BARRIER_REPAIR_ESCALATION = 20,

	CORE_MAX_HP = 500,

	VAULT_MAX_SLOTS = 6,

	MAX_DEFENSES = 15,
	SELL_REFUND_RATE = 0.5,

	TOTAL_WAVES = 8,
	BUILD_PHASE_DURATION = 18,
	SPAWN_INTERVAL_BASE = 1.4,

	INFILTRATOR_TRAVEL_TIME = 4,
	INFILTRATOR_STEAL_TIME = 2.5,

	VAULT_INCOME_INTERVAL = 8,

	BUILD_ZONE_SNAP_RADIUS = 8,

	BRAINROT_Y_OFFSET = 1.5,
}

return GameConfig
